name: sunhope_computer_software
description: "Sunhope computer software"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  easy_sidemenu: ^0.6.0
  dio: ^5.4.1
  json_annotation: ^4.8.1
  retrofit: ^4.1.0
  flutter_bloc: ^8.1.4
  equatable: ^2.0.5
  shared_preferences: ^2.2.2
  get: ^4.6.6
  intl: ^0.19.0
  page_transition: ^2.1.0
  pretty_dio_logger: ^1.3.1
  flutter_libserialport: ^0.2.3
  uuid: ^4.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  retrofit_generator: ^7.0.8
  build_runner: ^2.4.8
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true

  assets:
    - assets/
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700